apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux-gha-app
  labels:
    helm.sh/chart: flux-gha-app-0.1.6
    app.kubernetes.io/name: flux-gha-app
    app.kubernetes.io/instance: flux-gha-app
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: flux-gha-app
      app.kubernetes.io/instance: flux-gha-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flux-gha-app
        app.kubernetes.io/instance: flux-gha-app
    spec:
      imagePullSecrets:
        - name: regcred
      serviceAccountName: flux-gha-app
      containers:
        - name: flux-gha-app
          image: "ghcr.io/vdksystem/flux-gha-app:0.1.0"
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http