apiVersion: v1
kind: Service
metadata:
  name: flux-gha-app
  labels:
    helm.sh/chart: flux-gha-app-0.1.6
    app.kubernetes.io/name: flux-gha-app
    app.kubernetes.io/instance: flux-gha-app
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: flux-gha-app
    app.kubernetes.io/instance: flux-gha-app
