apiVersion: v2
name: flux-gha-app
description: A Helm chart for Kubernetes
maintainers:
  - name: vdksystem
    email: vdksystem@gmail.com
type: application
version: 0.1.2
appVersion: "0.1.0"
annotations:
  team: "adimen"