name: CI pipeline
on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  packages: write
  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      app: ${{ steps.filter.outputs.app }}
      charts: ${{ steps.filter.outputs.charts }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            charts:
              - 'charts/**'
            app:
              - 'Dockerfile'
              - 'app/**'
              - poetry.lock
              - pyproject.toml
  app-test:
    runs-on: ubuntu-latest
    needs:
      - changes
    if: ${{ needs.changes.outputs.app == 'true' }}
    steps:
      - uses: vdksystem/flux-gha-actions/app-test@main
      - uses: vdksystem/flux-gha-actions/docker-build-push@main
        id: build
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
  helm-release:
    runs-on: ubuntu-latest
    needs:
      - changes
    if: ${{ needs.changes.outputs.charts == 'true' }}
    steps:
      - uses: vdksystem/flux-gha-actions/helm-release@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
