name: CI pipeline for PR
on:
  pull_request:
    branches:
    - main
    types:
      - opened
      - synchronize
      - reopened
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      app: ${{ steps.filter.outputs.app }}
      charts: ${{ steps.filter.outputs.charts }}
    steps:
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          charts:
            - 'charts/**'
          app:
            - 'Dockerfile'
            - 'app/**'
            - poetry.lock
            - pyproject.toml
  helm-test:
    runs-on: ubuntu-latest
    needs:
      - changes
    if: ${{ needs.changes.outputs.charts == 'true' }}
    steps:
      - uses: actions/checkout@v3  # Temporary, until common action would be pushed to central repo
      - uses: ./workflows/actions/helm-lint-test

  app-test:
    runs-on: ubuntu-latest
    needs:
      - changes
    if: ${{ needs.changes.outputs.app == 'true' }}
    steps:
      - uses: actions/checkout@v3  # Temporary, until common action would be pushed to central repo
      - uses: ./workflows/actions/app-test
