name: CI pipeline for PR
on:
  pull_request:
    branches:
    - main
    types:
      - opened
      - synchronize
      - reopened
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: read
  packages: write

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      app: ${{ steps.filter.outputs.app }}
      charts: ${{ steps.filter.outputs.charts }}
    steps:
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          charts:
            - 'charts/**'
          app:
            - 'Dockerfile'
            - 'app/**'
            - poetry.lock
            - pyproject.toml
  helm-test:
    runs-on: ubuntu-latest
    needs:
      - changes
    permissions:
      packages: read
    if: ${{ needs.changes.outputs.charts == 'true' }}
    steps:
      - uses: vdksystem/flux-gha-actions/helm-lint-test@main
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

  app-test:
    runs-on: ubuntu-latest
    needs:
      - changes
    if: ${{ needs.changes.outputs.app == 'true' }}
    steps:
      - uses: vdksystem/flux-gha-actions/app-test@main
      - uses: vdksystem/flux-gha-actions/docker-build-push@main
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
