name: CI pipeline for PR
on:
  pull_request:
    branches:
    - main
    types:
      - opened
      - synchronize
      - reopened
jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/paths-filter@v2
      id: changes_charts
      with:
        filters: |
          charts:
            - 'charts/**'
  helm-test:
    runs-on: ubuntu-latest
    needs:
      - changes
    if: ${{ needs.changes.outputs.charts == 'true' }}
    steps:
      - uses: ./workflows/actions/helm-lint-test
