name: CI pipeline for PR
on:
  pull_request:
    branches:
    - main
    types:
      - opened
      - synchronize
      - reopened
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: read
  packages: write

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      app: ${{ steps.filter.outputs.app }}
      charts: ${{ steps.filter.outputs.charts }}
    steps:
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          charts:
            - 'charts/**'
          app:
            - 'Dockerfile'
            - 'app/**'
            - poetry.lock
            - pyproject.toml

  app-test:
    runs-on: ubuntu-latest
    needs:
      - changes
    if: ${{ needs.changes.outputs.app == 'true' }}
    outputs:
      tag: ${{ steps.build.outputs.tag }}
    steps:
      - uses: vdksystem/flux-gha-actions/app-test@main
      - uses: vdksystem/flux-gha-actions/docker-build-push@main
        id: build
        with:
          password: ${{ secrets.DOCKER_TOKEN }}
      - run: echo "${{ steps.build.outputs.tag }}"
      - run: echo "${{ steps.build.outputs }}"
  helm-test:
    runs-on: ubuntu-latest
    needs:
      - changes
      - app-test
    permissions: read-all
    if: |
      always() &&
      (needs.app-test.result == 'success' || needs.app-test.result == 'skipped') &&
      ${{ needs.changes.outputs.charts == 'true' }}
    steps:
      - uses: vdksystem/flux-gha-actions/helm-lint-test@main
        with:
          tag: ${{ needs.app-test.outputs.tag }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}